[package]
name = "authorities-browser-engine"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
legal-structure = { git = "https://github.com/eliziff/legal-structure-parser.git", rev = "2025715933f3bb31c9d0cfdd5f6be6ef39614fde", features = ["provider-text", "citator", "document-query"] }
serde_json = "1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
