// Generated by sync-publisher.mjs from Beaver shared/folder-pdf-match.mjs. Do not edit.
// Source SHA-256: 06608c31b138e08b86c4408cb16438516df2f17cb27df2958d8e4eb623c7e11d
// See THIRD_PARTY_NOTICES.md.
// shared/folder-pdf-match.mjs
var CANLII_PDF_NAME = /^(\d{4})([a-z]{2,10})(\d{1,5})(?: ?\(\d+\))?\.pdf$/iu;
var REPORTER_PDF_NAME = /^(\d{4})(scr|rcs)(\d*)_(\d+)(?: ?\(\d+\))?\.pdf$/iu;
var key = (call, text) => call("keyForText", { text: String(text || "") }).key;
var extract = (call, text) => call("extract", { text, offsetUnit: "utf16", options: { resolve: false, parallel: false } }).citations;
function canliiFiles(files) {
  const best = /* @__PURE__ */ new Map();
  for (const file of files) {
    const match = CANLII_PDF_NAME.exec(file.name);
    if (!match || (file.webkitRelativePath || "").split("/").length > 2) continue;
    const citation = `${match[1]} ${match[2].toUpperCase()} ${match[3]}`;
    if (!(best.get(citation)?.lastModified >= file.lastModified)) best.set(citation, file);
  }
  return [...best].map(([citation, file]) => ({ citation, file }));
}
function headerText(pages) {
  let text = "";
  for (const line of pages[0]?.lines || []) {
    if (/^\s*(?:\[1\]|1[.)])\s/u.test(line.text)) break;
    text += `${line.text}
`;
    if (text.length > 5e3) break;
  }
  return text;
}
function headerIdentities(pages, call) {
  const text = headerText(pages);
  return !text ? [] : extract(call, text).filter((c) => c.form === "full" && ["neutral", "can_lii", "reporter"].includes(c.format)).map((c) => ({ ...c.span, key: c.key, family: c.format }));
}
function scrRunningHead(pages, citations, call) {
  const head = (pages[0]?.lines || []).slice(0, 6).map((line) => line.text).join(" ");
  return call("matchesReporterHeader", { text: head, citations });
}
function verifyIdentity(pages, record, call) {
  const aliases = record.aliases.flatMap((alias) => extract(call, alias));
  const identities = headerIdentities(pages, call), accepted = new Set(aliases.map((c) => c.key).filter(Boolean));
  const own = identities.filter((i) => i.family === "neutral");
  const candidates = own.length ? own.slice(0, 1) : identities;
  if ((!own.length || !aliases.some((c) => c.format === "neutral")) && scrRunningHead(pages, aliases, call)) return;
  if (!candidates.some((i) => i.key && accepted.has(i.key))) throw new Error(own.length ? `Wrong PDF: its opening citation is ${own[0].text}, not ${record.citation}.` : "The opening citation could not be verified. Keep this file unbound and check its first page.");
}
var words = (text) => String(text || "").normalize("NFKC").toLowerCase().match(/[\p{L}\p{N}]+/gu) || [];
var referenceText = (text) => ` ${words(text).join(" ")} `;
var normalized = /* @__PURE__ */ new WeakMap();
async function matchFolderPdf(filename, pages, records, call, reference = (record) => record.referenceText) {
  const named = CANLII_PDF_NAME.exec(filename), reporter = REPORTER_PDF_NAME.exec(filename);
  const nameKey = key(call, named ? `${named[1]} ${named[2].toUpperCase()} ${named[3]}` : reporter ? `[${reporter[1]}] ${reporter[3]} ${reporter[2].toUpperCase()} ${reporter[4]}` : filename.replace(/\.pdf$/iu, ""));
  const namedRecords = nameKey ? records.filter((r) => r.aliases.some((a) => key(call, a) === nameKey)) : [];
  const tokens = words(pages.map((p) => p.lines.map((l) => l.text).join("\n")).join("\n"));
  if (tokens.length < 12) return namedRecords.length === 1 ? { record: namedRecords[0], method: "filename" } : null;
  const header = headerIdentities(pages, call), neutral = header.filter((c) => c.family === "neutral");
  const identities = new Set((neutral.length ? neutral.slice(0, 1) : header).map((c) => c.key).filter(Boolean));
  const candidates = records.filter((r) => r.aliases.some((a) => identities.has(key(call, a))));
  const verified = candidates.filter((r) => {
    try {
      verifyIdentity(pages, r, call);
      return true;
    } catch {
      return false;
    }
  });
  if (verified.length === 1) return { record: verified[0], method: "citation" };
  if (verified.length > 1 || neutral.length) return null;
  const phrases = [...new Set(Array.from(
    { length: Math.floor(Math.min(tokens.length, 1200) / 12) },
    (_, i) => ` ${tokens.slice(i * 12, i * 12 + 12).join(" ")} `
  ))];
  const references = await Promise.all(records.map(async (record) => {
    if (!normalized.has(record)) normalized.set(record, referenceText(await reference(record)));
    return normalized.get(record);
  }));
  const matches = references.map((ref) => phrases.map((p) => ref.includes(p)));
  const supported = records.filter((_, i) => {
    const count = matches[i].filter(Boolean).length;
    const unique = matches[i].filter((yes, j) => yes && !matches.some((other, k) => k !== i && other[j])).length;
    return count > phrases.length / 2 && unique >= 2;
  });
  return supported.length === 1 ? { record: supported[0], method: "text" } : null;
}
export {
  CANLII_PDF_NAME,
  canliiFiles,
  headerIdentities,
  headerText,
  matchFolderPdf,
  referenceText,
  verifyIdentity
};
