// Generated by sync-publisher.mjs from Beaver backend/src/lib/legalSourcePresentation.ts. Do not edit.
// Source SHA-256: 0151adb38c72f0e4f31e95e499f14e8c553f2833b9971f77b407431a916c3d1f
// See THIRD_PARTY_NOTICES.md.
// backend/src/lib/text.ts
function normalizeWhitespace(text) {
  return text.trim().replace(/[ \t\r\n\f\v]+/gu, " ");
}

// backend/src/lib/legalSourcePresentation.ts
function decodeHtmlEntities(value) {
  return value.replace(/&nbsp;/giu, " ").replace(/&amp;/giu, "&").replace(/&lt;/giu, "<").replace(/&gt;/giu, ">").replace(/&quot;/giu, '"').replace(/&apos;|&#39;/giu, "'").replace(/&#(\d+);/gu, (match, code) => {
    const value2 = Number.parseInt(code, 10);
    return value2 <= 1114111 ? String.fromCodePoint(value2) : match;
  }).replace(/&#x([0-9a-f]+);/giu, (match, code) => {
    const value2 = Number.parseInt(code, 16);
    return value2 <= 1114111 ? String.fromCodePoint(value2) : match;
  });
}
function plainInlineText(value) {
  return normalizeWhitespace(decodeHtmlEntities(value.replace(/<script\b[\s\S]*?<\/script\s*>/giu, " ").replace(/<style\b[\s\S]*?<\/style\s*>/giu, " ").replace(/\[([^\]\r\n]+)\]\([^)\r\n]+\)/gu, "$1").replace(/<[^>]+>/gu, " ").replace(/\\([\\`*_{}\[\]()#+.!>~-])/gu, "$1").replace(/[*_`~]/gu, "")));
}
function httpUrl(rawUrl, baseUrl) {
  try {
    const url = new URL(decodeHtmlEntities(rawUrl.trim()), baseUrl);
    if (!["http:", "https:"].includes(url.protocol)) return null;
    if (url.username || url.password) return null;
    return url;
  } catch {
    return null;
  }
}
var DECISIA_HOSTS = /* @__PURE__ */ new Set([
  "coadecisions.ontariocourts.ca",
  "decisions.courts.ns.ca",
  "decisia.lexum.com",
  "decision.tcc-cci.gc.ca",
  "decisions.cart-crac.gc.ca",
  "decisions.chrt-tcdp.gc.ca",
  "decisions.citt-tcce.gc.ca",
  "decisions.cmac-cacm.ca",
  "decisions.courts.ns.ca",
  "decisions.ct-tc.gc.ca",
  "decisions.fca-caf.gc.ca",
  "decisions.fct-cf.gc.ca",
  "decisions.fpslreb-crtespf.gc.ca",
  "decisions.psdpt-tpfd.gc.ca",
  "decisions.scc-csc.ca",
  "decisions.sct-trp.ca",
  "decisions.sst-tss.gc.ca",
  "decisions.tatc.gc.ca"
]);
function decisiaIndexUrl(rawUrl) {
  const source = httpUrl(String(rawUrl));
  if (!source || source.protocol !== "https:" || source.port || !DECISIA_HOSTS.has(source.hostname.toLowerCase()) || !/^\/[a-z0-9/_-]+\/item\/\d+\/index\.do$/iu.test(source.pathname)) return null;
  source.search = "";
  source.hash = "";
  return source;
}
function publisherPdfSourceUrl(raw) {
  let url;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  const bc = ["www.bccourts.ca", "bccourts.ca"].includes(url.hostname);
  const validPath = DECISIA_HOSTS.has(url.hostname) ? /^\/[a-z0-9/_-]+\/(?:item\/\d+\/index\.do|\d+\/document\.do)$/i.test(url.pathname) : bc && /^\/jdb-txt\/(?:sc|ca)\/[a-z0-9/_-]+\.(?:htm|html|pdf)$/i.test(url.pathname);
  if (bc && url.protocol === "http:") url.protocol = "https:";
  if (url.protocol !== "https:" || url.port || url.username || url.password || !validPath || /[%\\]/.test(url.pathname)) return null;
  url.hash = "";
  url.search = "";
  return url;
}
function publisherPdfCandidate(rawUrl) {
  const source = decisiaIndexUrl(rawUrl);
  if (source) {
    source.pathname = source.pathname.replace(/\/item\/(\d+)\/index\.do$/iu, "/$1/1/document.do");
    return source.toString();
  }
  const publisher = httpUrl(String(rawUrl));
  if (!publisher || publisher.protocol !== "https:" || publisher.port) return null;
  return LEGISLATION_PDFS[publisher.hostname.toLowerCase()]?.(publisher) ?? null;
}
var pathPart = /^[\p{L}\p{N}][\p{L}\p{N} .,_'()&-]*$/u;
var LEGISLATION_PDFS = {
  "laws-lois.justice.gc.ca": federalLegislationPdf,
  "lois-laws.justice.gc.ca": federalLegislationPdf,
  "kings-printer.alberta.ca": ({ pathname, searchParams }) => {
    const page = searchParams.get("page"), type = searchParams.get("leg_type");
    return pathname === "/1266.cfm" && page && /^[a-z0-9][a-z0-9_-]*\.cfm$/iu.test(page) && (type === "Acts" || type === "Regs") ? `https://kings-printer.alberta.ca/documents/${type}/${page.slice(0, -4)}.pdf` : null;
  },
  "web2.gov.mb.ca": ({ pathname }) => {
    const act = /^\/laws\/statutes\/ccsm\/([a-z])0*(\d+)(?:-(\d+))?\.php$/iu.exec(pathname);
    if (act) return `https://web2.gov.mb.ca/laws/statutes/ccsm/_pdf.php?cap=${act[1].toLowerCase()}${act[2]}${act[3] ? `.${act[3]}` : ""}`;
    const regulation = /^\/laws\/regs\/current\/0*(\d+)-(\d+)(r?)\.php$/iu.exec(pathname);
    return regulation ? `https://web2.gov.mb.ca/laws/regs/current/_pdf-regs.php?reg=${regulation[1]}/${regulation[2]}${regulation[3] ? "%20R" : ""}` : null;
  },
  "laws.gnb.ca": newBrunswickLegislationPdf,
  "lois.gnb.ca": newBrunswickLegislationPdf,
  "nslegislature.ca": ({ pathname }) => {
    const name = /^\/sites\/default\/files\/legc\/statutes(?: HTML)?\/([^/]+)\.html?$/iu.exec(decodeURIComponent(pathname))?.[1];
    return name && pathPart.test(name) ? `https://nslegislature.ca/sites/default/files/legc/statutes/${encodeURI(name)}.pdf` : null;
  }
};
function federalLegislationPdf({ pathname }) {
  const path = decodeURIComponent(pathname);
  const id = /^\/(?:eng|fra)\/XML\/([^/]+)\.xml$/iu.exec(path)?.[1] ?? /^\/(?:eng\/(?:acts|regulations)|fra\/(?:lois|reglements))\/([^/]+)\/?(?:[^/]*\.html)?$/iu.exec(path)?.[1];
  if (!id || !pathPart.test(id) || id.includes("..") || id.endsWith(".")) return null;
  const english = id.replace(/^DORS-/u, "SOR-").replace(/^TR-/u, "SI-").replace(/^C\.R\.C\.,_ch\._/u, "C.R.C.,_c._");
  return `https://laws-lois.justice.gc.ca/PDF/${english}.pdf`;
}
function newBrunswickLegislationPdf({ pathname }) {
  const [, corpus, id] = /^\/(?:en|fr)\/document\/(cs|cr|lc|rc)\/([^/]+)$/iu.exec(decodeURIComponent(pathname)) ?? [];
  return id && pathPart.test(id) ? `https://laws.gnb.ca/en/pdf/${{ lc: "cs", rc: "cr" }[corpus.toLowerCase()] ?? corpus.toLowerCase()}/${encodeURI(id)}.pdf` : null;
}
var LEGISLATION_PDF_PATHS = {
  "laws-lois.justice.gc.ca": /^\/PDF\/[\p{L}\p{N}][\p{L}\p{N}.,_-]*\.pdf$/u,
  "kings-printer.alberta.ca": /^\/documents\/(?:Acts|Regs)\/[a-z0-9][a-z0-9_-]*\.pdf$/iu,
  "web2.gov.mb.ca": /^\/laws\/(?:statutes\/ccsm\/_pdf\.php\?cap=[a-z]\d+(?:\.\d+)?|regs\/current\/_pdf-regs\.php\?reg=\d+\/\d+(?: R)?)$/iu,
  "laws.gnb.ca": /^\/en\/pdf\/c[sr]\/[\p{L}\p{N}][\p{L}\p{N} .,_-]*\.pdf$/u,
  "nslegislature.ca": /^\/sites\/default\/files\/legc\/statutes\/[\p{L}\p{N}][\p{L}\p{N} .,_'()&-]*\.pdf$/u,
  "www.justice.gov.nt.ca": /^\/en\/files\/legislation\/[a-z0-9-]+\/[a-z0-9.-]+\.pdf$/iu,
  "www.princeedwardisland.ca": /^\/sites\/default\/files\/[a-z0-9]+\/[\p{L}\p{N}][\p{L}\p{N} .,_'()&;-]*\.pdf$/u,
  "publications.saskatchewan.ca": /^\/api\/v1\/products\/\d+\/formats\/\d+\/download$/u,
  "laws.yukon.ca": /^\/cms\/images\/LEGISLATION\/[A-Za-z0-9/_.-]+\.pdf$/u
};
function legislationPdfUrl(raw) {
  const url = httpUrl(String(raw));
  const pattern = url && LEGISLATION_PDF_PATHS[url.hostname.toLowerCase()];
  if (!url || !pattern || url.protocol !== "https:" || url.port || url.hash) return null;
  let path;
  try {
    path = decodeURIComponent(url.pathname) + decodeURIComponent(url.search);
  } catch {
    return null;
  }
  return !path.includes("..") && !path.includes("\\") && pattern.test(path) ? url : null;
}
var LEGISLATION_PDF_HOSTS = Object.keys(LEGISLATION_PDF_PATHS);
function publisherOpenUrl(pageUrl, pdfUrl) {
  const [page, pdf] = [pageUrl, pdfUrl].map((raw) => {
    const url = raw ? httpUrl(raw) : null;
    if (!url || /\/robocop\//iu.test(url.pathname)) return null;
    url.protocol = "https:";
    return url;
  });
  if (pdf && (!page || pdf.origin === page.origin)) return pdf.toString();
  return page && decisiaIndexUrl(page)?.hostname === "decisions.scc-csc.ca" ? publisherPdfCandidate(page) : page?.toString() ?? null;
}
var attributePattern = (name) => new RegExp(`\\b${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'=<>\`]+))`, "iu");
var CLASS_ATTRIBUTE = attributePattern("class");
var ID_ATTRIBUTE = attributePattern("id");
var HREF_ATTRIBUTE = attributePattern("href");
var SRC_ATTRIBUTE = attributePattern("src");
var ACTION_ATTRIBUTE = attributePattern("action");
function attributeValue(attributes, pattern) {
  const match = attributes.match(pattern);
  return match?.[1] ?? match?.[2] ?? match?.[3] ?? "";
}
function publisherChallengeUrl(markup, rawUrl) {
  const source = httpUrl(String(rawUrl));
  if (!source || source.protocol !== "https:") return null;
  const challenge = (raw) => {
    const url = httpUrl(raw, source);
    return url?.origin === source.origin && /^\/robocop\/captcha\/(?:en|fr)\/query\.do$/iu.test(url.pathname) ? url.toString() : null;
  };
  const own = challenge(source.toString());
  if (own) return own;
  for (const match of markup.matchAll(/<iframe\b([^>]*)>/giu)) {
    const found = challenge(attributeValue(match[1], SRC_ATTRIBUTE));
    if (found) return found;
  }
  if (decisiaIndexUrl(source)) {
    for (const match of markup.matchAll(/<div\b([^>]*)>\s*<form\b([^>]*)>/giu)) {
      if (attributeValue(match[1], ID_ATTRIBUTE) !== "captchaForm") continue;
      const action = httpUrl(attributeValue(match[2], ACTION_ATTRIBUTE), source);
      if (action?.origin === source.origin && action.pathname === "/robocop/captcha/eval.do")
        return source.toString();
    }
  }
  return null;
}
function controlledDecisiaPdfUrl(controls, source) {
  for (const control of controls) {
    for (const link of markupLinks(control)) {
      const candidate = httpUrl(link.url, source);
      if (candidate?.origin === source.origin && /\/document\.do$/iu.test(candidate.pathname)) return candidate.toString();
    }
  }
  return null;
}
function verifiedDecisiaPdf(markup, rawUrl) {
  const source = decisiaIndexUrl(rawUrl);
  if (!source) return null;
  const pdfOnlyControls = [...markup.matchAll(
    /<([a-z][\w:-]*)\b([^>]*\bdecisia-decision-pdf-only\b[^>]*)>([\s\S]*?)<\/\1\s*>/giu
  )].map((match) => match[3]);
  const pdfOnlyUrl = controlledDecisiaPdfUrl(pdfOnlyControls, source);
  if (pdfOnlyUrl) return { url: pdfOnlyUrl, pdfOnly: true };
  const documentControls = [];
  for (const match of markup.matchAll(/<(?:li|div)\b([^>]*\bdocuments\b[^>]*)>([\s\S]*?)<\/(?:li|div)\s*>/giu)) {
    if (attributeValue(match[1], CLASS_ATTRIBUTE).split(/\s+/u).includes("documents")) {
      documentControls.push(match[2]);
    }
  }
  const url = controlledDecisiaPdfUrl(documentControls, source);
  return url ? { url, pdfOnly: false } : null;
}
function markupLinks(markup) {
  const links = [];
  for (const match of markup.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a\s*>/giu)) {
    const url = attributeValue(match[1], HREF_ATTRIBUTE);
    if (!url) continue;
    links.push({
      url,
      label: plainInlineText(match[2])
    });
  }
  return links;
}
function rankedPublisherPdfLinks(markup, rawUrl) {
  const source = httpUrl(String(rawUrl));
  if (!source) return [];
  const links = markupLinks(markup).map((link) => ({ ...link, frame: false }));
  for (const match of markup.matchAll(/<iframe\b([^>]*)>/giu)) {
    const url = attributeValue(match[1], SRC_ATTRIBUTE);
    if (url) links.push({ url, label: "", frame: true });
  }
  return links.map(({ url: raw, label, frame }, position) => {
    const url = httpUrl(raw, source);
    if (!url) return null;
    const clue = `${label} ${url.pathname} ${url.search}`.toLowerCase();
    let score = url.pathname.toLowerCase().endsWith(".pdf") ? 50 : 0;
    if (frame && url.origin === source.origin && url.pathname === source.pathname && url.searchParams.get("iframe") === "true") score += 90;
    if (url.pathname.toLowerCase().includes("/document.do")) score += 90;
    if (/download pdf|view pdf|full[- ]text pdf/u.test(clue)) score += 80;
    else if (/download|viewcontent|article\/view|galley/u.test(clue)) score += 35;
    else if (label.toLowerCase() === "pdf") score += 60;
    if (url.origin === source.origin) score += 15;
    return score >= 50 ? { score, position, url: url.toString() } : null;
  }).filter((item) => Boolean(item)).sort((left, right) => right.score - left.score || left.position - right.position).map(({ url }) => url);
}
export {
  DECISIA_HOSTS,
  LEGISLATION_PDF_HOSTS,
  decisiaIndexUrl,
  legislationPdfUrl,
  plainInlineText,
  publisherChallengeUrl,
  publisherOpenUrl,
  publisherPdfCandidate,
  publisherPdfSourceUrl,
  rankedPublisherPdfLinks,
  verifiedDecisiaPdf
};
