var ortWasmThreaded = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,k,l,aa=new Promise((a,b)=>{k=a;l=b}),ba="object"==typeof window,m="undefined"!=typeof WorkerGlobalScope,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,q=m&&self.name?.startsWith("em-pthread");if(n){const {createRequire:a}=await import("module");var require=a(import.meta.url),r=require("worker_threads");global.Worker=r.Worker;q=(m=!r.ab)&&"em-pthread"==r.workerData}
f.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(f.Na||(f.Na=new Map)).set(a,b)};f.unmountExternalData=()=>{delete f.Na};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,cb:!0})).buffer.constructor,ca=Object.assign({},f),da="./this.program",t=(a,b)=>{throw b;},u="",ea,w;
if(n){var fs=require("fs"),fa=require("path");import.meta.url.startsWith("data:")||(u=fa.dirname(require("url").fileURLToPath(import.meta.url))+"/");w=a=>{a=x(a)?new URL(a):a;return fs.readFileSync(a)};ea=async a=>{a=x(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);t=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||m)m?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(u=document.currentScript.src),_scriptName&&(u=_scriptName),u.startsWith("blob:")?u="":u=u.slice(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1),n||(m&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=async a=>{if(x(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});
var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);});var ha=console.log.bind(console),ia=console.error.bind(console);n&&(ha=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),ia=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var ja=ha,y=ia;Object.assign(f,ca);ca=null;var z=f.wasmBinary,A,ka,B=!1,C,D,la,ma,na,oa,pa,E,qa,x=a=>a.startsWith("file://");function F(){A.buffer!=D.buffer&&G();return D}function H(){A.buffer!=D.buffer&&G();return la}
function sa(){A.buffer!=D.buffer&&G();return ma}function I(){A.buffer!=D.buffer&&G();return na}function J(){A.buffer!=D.buffer&&G();return oa}function ta(){A.buffer!=D.buffer&&G();return pa}function K(){A.buffer!=D.buffer&&G();return qa}
if(q){var ua;if(n){var va=r.parentPort;va.on("message",b=>onmessage({data:b}));Object.assign(globalThis,{self:global,postMessage:b=>va.postMessage(b)})}var wa=!1;y=function(...b){b=b.join(" ");n?fs.writeSync(2,b+"\n"):console.error(b)};self.alert=function(...b){postMessage({Ma:"alert",text:b.join(" "),Wa:L()})};self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.Ma;if("load"===d){let e=[];self.onmessage=g=>e.push(g);self.startWorker=()=>{postMessage({Ma:"loaded"});
for(let g of e)a(g);self.onmessage=a};for(const g of c.Sa)if(!f[g]||f[g].proxy)f[g]=(...h)=>{postMessage({Ma:"callHandler",Ra:g,args:h})},"print"==g&&(ja=f[g]),"printErr"==g&&(y=f[g]);A=c.Ya;G();ua(c.Za)}else if("run"===d){xa(c.La);ya(c.La,0,0,1,0,0);za();Aa(c.La);wa||=!0;try{Ba(c.Ua,c.Pa)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?wa&&M():d&&(y(`worker: received unknown command ${d}`),y(c)))}catch(e){throw Ca(),e;}}self.onmessage=a}
function G(){var a=A.buffer;f.HEAP8=D=new Int8Array(a);f.HEAP16=ma=new Int16Array(a);f.HEAPU8=la=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAP32=na=new Int32Array(a);f.HEAPU32=oa=new Uint32Array(a);f.HEAPF32=pa=new Float32Array(a);f.HEAPF64=qa=new Float64Array(a);f.HEAP64=E=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}q||(A=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0}),G());function Da(){q?startWorker(f):O.W()}var P=0,Q=null;
function Ea(){P--;if(0==P&&Q){var a=Q;Q=null;a()}}function R(a){a="Aborted("+a+")";y(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");l(a);throw a;}var Fa;async function Ga(a){if(!z)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==Fa&&z)a=new Uint8Array(z);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ha(a,b){try{var c=await Ga(a);return await WebAssembly.instantiate(c,b)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),R(d)}}async function Ia(a){var b=Fa;if(!z&&"function"==typeof WebAssembly.instantiateStreaming&&!x(b)&&!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){y(`wasm streaming compile failed: ${d}`),y("falling back to ArrayBuffer instantiation")}return Ha(b,a)}
function Ja(){Ka={B:La,c:Ma,T:Na,w:Oa,y:Pa,o:Qa,R:Ra,K:Sa,Q:Ta,h:Ua,x:Va,u:Wa,S:Xa,v:Ya,J:Za,N:$a,q:ab,C:bb,m:cb,f:db,M:Aa,j:eb,F:fb,G:gb,H:hb,D:ib,E:jb,n:kb,I:lb,A:mb,V:nb,g:ob,k:pb,U:qb,i:rb,r:sb,b:tb,s:ub,p:vb,O:wb,P:xb,z:yb,d:zb,e:Ab,L:Bb,t:Cb,a:A,l:Db};return{a:Ka}}
var Fb={142172:(a,b,c,d,e)=>{if("undefined"==typeof f||!f.Na)return 1;a=Eb(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=f.Na.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const g=a.subarray(b,b+c);switch(e){case 0:H().set(g,d>>>0);break;case 1:f.$a?f.$a(d,g):f.bb(d,g);break;default:return 4}return 0}catch{return 4}}};class Gb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Hb=a=>{a.terminate();a.onmessage=()=>{}},Ib=[],Lb=a=>{0==S.length&&(Jb(),Kb(S[0]));var b=S.pop();if(!b)return 6;T.push(b);U[a.La]=b;b.La=a.La;var c={Ma:"run",Ua:a.Ta,Pa:a.Pa,La:a.La};n&&b.unref();b.postMessage(c,a.Qa);return 0},V=0,X=(a,b,...c)=>{for(var d=2*c.length,e=Mb(),g=Nb(8*d),h=g>>>3,p=0;p<c.length;p++){var v=c[p];"bigint"==typeof v?(E[h+2*p]=1n,E[h+2*p+1]=v):(E[h+2*p]=0n,K()[h+2*p+1>>>0]=v)}a=Ob(a,0,d,g,b);W(e);return a};
function Db(a){if(q)return X(0,1,a);C=a;if(!(0<V)){for(var b of T)Hb(b);for(b of S)Hb(b);S=[];T=[];U={};B=!0}t(a,new Gb(a))}function Pb(a){if(q)return X(1,0,a);yb(a)}var yb=a=>{C=a;if(q)throw Pb(a),"unwind";Db(a)},S=[],T=[],Qb=[],U={};function Rb(){for(var a=f.numThreads-1;a--;)Jb();Ib.unshift(()=>{P++;Sb(()=>Ea())})}var Ub=a=>{var b=a.La;delete U[b];S.push(a);T.splice(T.indexOf(a),1);a.La=0;Tb(b)};function za(){Qb.forEach(a=>a())}
var Kb=a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var h=g.Ma;if(g.Oa&&g.Oa!=L()){var p=U[g.Oa];p?p.postMessage(g,g.Qa):y(`Internal error! Worker sent a message "${h}" to target pthread ${g.Oa}, but that thread no longer exists!`)}else if("checkMailbox"===h)M();else if("spawnThread"===h)Lb(g);else if("cleanupThread"===h)Ub(U[g.Va]);else if("loaded"===h)a.loaded=!0,n&&!a.La&&a.unref(),b(a);else if("alert"===h)alert(`Thread ${g.Wa}: ${g.text}`);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===
h)f[g.Ra](...g.args);else h&&y(`worker sent an unknown command ${h}`)};a.onerror=g=>{y(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};n&&(a.on("message",g=>a.onmessage({data:g})),a.on("error",g=>a.onerror(g)));var c=[],d=[],e;for(e of d)f.propertyIsEnumerable(e)&&c.push(e);a.postMessage({Ma:"load",Sa:c,Ya:A,Za:ka})});function Sb(a){q?a():Promise.all(S.map(Kb)).then(a)}
function Jb(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});S.push(a)}var xa=a=>{G();var b=J()[a+52>>>2>>>0];a=J()[a+56>>>2>>>0];Vb(b,b-a);W(b)},Wb,Ba=(a,b)=>{V=0;a=Wb.get(a)(b);0<V?C=a:Xb(a)};function Yb(a,b,c,d){return q?X(2,1,a,b,c,d):La(a,b,c,d)}
function La(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(q&&0===e.length)return Yb(a,b,c,d);a={Ta:c,La:a,Pa:d,Qa:e};return q?(a.Ma="spawnThread",postMessage(a,e),0):Lb(a)}
var Zb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,$b=(a,b=0,c=NaN)=>{b>>>=0;var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Zb)return Zb.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Eb=(a,b)=>(a>>>=0)?$b(H(),a,b):"";function Ma(a,b,c){return q?X(3,1,a,b,c):0}function Na(a,b){if(q)return X(4,1,a,b)}
var Y=(a,b,c)=>{var d=H();b>>>=0;if(0<c){var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var p=a.charCodeAt(++g);h=65536+((h&1023)<<10)|p&1023}if(127>=h){if(b>=c)break;d[b++>>>0]=h}else{if(2047>=h){if(b+1>=c)break;d[b++>>>0]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++>>>0]=224|h>>12}else{if(b+3>=c)break;d[b++>>>0]=240|h>>18;d[b++>>>0]=128|h>>12&63}d[b++>>>0]=128|h>>6&63}d[b++>>>0]=128|h&63}}d[b>>>0]=0;a=b-e}else a=0;return a};
function Oa(a,b){if(q)return X(5,1,a,b)}function Pa(a,b,c){if(q)return X(6,1,a,b,c)}function Qa(a,b,c){return q?X(7,1,a,b,c):0}function Ra(a,b){if(q)return X(8,1,a,b)}function Sa(a,b,c){if(q)return X(9,1,a,b,c)}function Ta(a,b,c,d){if(q)return X(10,1,a,b,c,d)}function Ua(a,b,c,d){if(q)return X(11,1,a,b,c,d)}function Va(a,b,c,d){if(q)return X(12,1,a,b,c,d)}function Wa(a){if(q)return X(13,1,a)}function Xa(a,b){if(q)return X(14,1,a,b)}function Ya(a,b,c){if(q)return X(15,1,a,b,c)}var Za=()=>R("");
function $a(a){ya(a>>>0,!m,1,!ba,131072,!1);za()}var ac=a=>{if(!B)try{if(a(),!(0<V))try{q?Xb(C):yb(C)}catch(b){b instanceof Gb||"unwind"==b||t(1,b)}}catch(b){b instanceof Gb||"unwind"==b||t(1,b)}};function Aa(a){a>>>=0;"function"===typeof Atomics.Xa&&(Atomics.Xa(I(),a>>>2,a).value.then(M),a+=128,Atomics.store(I(),a>>>2,1))}var M=()=>{var a=L();a&&(Aa(a),ac(bc))};function ab(a,b){a>>>=0;a==b>>>0?setTimeout(M):q?postMessage({Oa:a,Ma:"checkMailbox"}):(a=U[a])&&a.postMessage({Ma:"checkMailbox"})}
var cc=[];function bb(a,b,c,d,e){b>>>=0;d/=2;cc.length=d;c=e>>>0>>>3;for(e=0;e<d;e++)cc[e]=E[c+2*e]?E[c+2*e+1]:K()[c+2*e+1>>>0];return(b?Fb[b]:dc[a])(...cc)}var cb=()=>{V=0};function db(a){a>>>=0;q?postMessage({Ma:"cleanupThread",Va:a}):Ub(U[a])}function eb(a){n&&U[a>>>0].ref()}
function fb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);I()[b>>>2>>>0]=a.getUTCSeconds();I()[b+4>>>2>>>0]=a.getUTCMinutes();I()[b+8>>>2>>>0]=a.getUTCHours();I()[b+12>>>2>>>0]=a.getUTCDate();I()[b+16>>>2>>>0]=a.getUTCMonth();I()[b+20>>>2>>>0]=a.getUTCFullYear()-1900;I()[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;I()[b+28>>>2>>>0]=a}
var ec=a=>0===a%4&&(0!==a%100||0===a%400),fc=[0,31,60,91,121,152,182,213,244,274,305,335],gc=[0,31,59,90,120,151,181,212,243,273,304,334];
function gb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);I()[b>>>2>>>0]=a.getSeconds();I()[b+4>>>2>>>0]=a.getMinutes();I()[b+8>>>2>>>0]=a.getHours();I()[b+12>>>2>>>0]=a.getDate();I()[b+16>>>2>>>0]=a.getMonth();I()[b+20>>>2>>>0]=a.getFullYear()-1900;I()[b+24>>>2>>>0]=a.getDay();var c=(ec(a.getFullYear())?fc:gc)[a.getMonth()]+a.getDate()-1|0;I()[b+28>>>2>>>0]=c;I()[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;I()[b+32>>>2>>>0]=a}
function hb(a){a>>>=0;var b=new Date(I()[a+20>>>2>>>0]+1900,I()[a+16>>>2>>>0],I()[a+12>>>2>>>0],I()[a+8>>>2>>>0],I()[a+4>>>2>>>0],I()[a>>>2>>>0],0),c=I()[a+32>>>2>>>0],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(g,e);0>c?I()[a+32>>>2>>>0]=Number(e!=g&&h==d):0<c!=(h==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));I()[a+24>>>2>>>0]=b.getDay();c=(ec(b.getFullYear())?fc:gc)[b.getMonth()]+
b.getDate()-1|0;I()[a+28>>>2>>>0]=c;I()[a>>>2>>>0]=b.getSeconds();I()[a+4>>>2>>>0]=b.getMinutes();I()[a+8>>>2>>>0]=b.getHours();I()[a+12>>>2>>>0]=b.getDate();I()[a+16>>>2>>>0]=b.getMonth();I()[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function ib(a,b,c,d,e,g,h){return q?X(16,1,a,b,c,d,e,g,h):-52}function jb(a,b,c,d,e,g){if(q)return X(17,1,a,b,c,d,e,g)}var Z={},tb=()=>performance.timeOrigin+performance.now();
function kb(a,b){if(q)return X(18,1,a,b);Z[a]&&(clearTimeout(Z[a].id),delete Z[a]);if(!b)return 0;var c=setTimeout(()=>{delete Z[a];ac(()=>hc(a,performance.timeOrigin+performance.now()))},b);Z[a]={id:c,eb:b};return 0}
function lb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var h=Math.max(g,e);J()[a>>>2>>>0]=60*h;I()[b>>>2>>>0]=Number(g!=e);b=p=>{var v=Math.abs(p);return`UTC${0<=p?"-":"+"}${String(Math.floor(v/60)).padStart(2,"0")}${String(v%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(Y(a,c,17),Y(b,d,17)):(Y(a,d,17),Y(b,c,17))}var pb=()=>Date.now(),ic=1;
function mb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(ic)a=performance.timeOrigin+performance.now();else return 52;E[c>>>0>>>3]=BigInt(Math.round(1E6*a));return 0}var jc=[];function nb(a,b,c){a>>>=0;b>>>=0;c>>>=0;jc.length=0;for(var d;d=H()[b++>>>0];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;jc.push(112==d?J()[c>>>2>>>0]:106==d?E[c>>>3]:105==d?I()[c>>>2>>>0]:K()[c>>>3>>>0]);c+=e?8:4}return Fb[a](...jc)}var ob=()=>{};function qb(a,b){return y(Eb(a>>>0,b>>>0))}
var rb=()=>{V+=1;throw"unwind";};function sb(){return 4294901760}var ub=()=>n?require("os").cpus().length:navigator.hardwareConcurrency;function vb(a){a>>>=0;var b=H().length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-A.buffer.byteLength+65535)/65536|0;try{A.grow(d);G();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1}
var kc={},mc=()=>{if(!lc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in kc)void 0===kc[b]?delete a[b]:a[b]=kc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lc=c}return lc},lc;
function wb(a,b){if(q)return X(19,1,a,b);a>>>=0;b>>>=0;var c=0;mc().forEach((d,e)=>{var g=b+c;e=J()[a+4*e>>>2>>>0]=g;for(g=0;g<d.length;++g)F()[e++>>>0]=d.charCodeAt(g);F()[e>>>0]=0;c+=d.length+1});return 0}function xb(a,b){if(q)return X(20,1,a,b);a>>>=0;b>>>=0;var c=mc();J()[a>>>2>>>0]=c.length;var d=0;c.forEach(e=>d+=e.length+1);J()[b>>>2>>>0]=d;return 0}function zb(a){return q?X(21,1,a):52}function Ab(a,b,c,d){return q?X(22,1,a,b,c,d):52}function Bb(a,b,c,d){return q?X(23,1,a,b,c,d):70}
var nc=[null,[],[]];function Cb(a,b,c,d){if(q)return X(24,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;for(var e=0,g=0;g<c;g++){var h=J()[b>>>2>>>0],p=J()[b+4>>>2>>>0];b+=8;for(var v=0;v<p;v++){var N=H()[h+v>>>0],ra=nc[a];0===N||10===N?((1===a?ja:y)($b(ra)),ra.length=0):ra.push(N)}e+=p}J()[d>>>2>>>0]=e;return 0}q||Rb();var dc=[Db,Pb,Yb,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,ib,jb,kb,wb,xb,zb,Ab,Bb,Cb],Ka,O;
(async function(){function a(d,e){O=d.exports;O=oc();Qb.push(O.ya);Wb=O.za;ka=e;Ea();return O}P++;var b=Ja();if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{a(e,g);d(e.exports)})});if(q)return new Promise(d=>{ua=e=>{var g=new WebAssembly.Instance(e,Ja());d(a(g,e))}});Fa??=f.locateFile?f.locateFile?f.locateFile("ort-wasm-simd-threaded.wasm",u):u+"ort-wasm-simd-threaded.wasm":(new URL("ort-wasm-simd-threaded.wasm",import.meta.url)).href;try{var c=await Ia(b);return a(c.instance,
c.module)}catch(d){return l(d),Promise.reject(d)}})();f._OrtInit=(a,b)=>(f._OrtInit=O.X)(a,b);f._OrtGetLastError=(a,b)=>(f._OrtGetLastError=O.Y)(a,b);f._OrtCreateSessionOptions=(a,b,c,d,e,g,h,p,v,N)=>(f._OrtCreateSessionOptions=O.Z)(a,b,c,d,e,g,h,p,v,N);f._OrtAppendExecutionProvider=(a,b,c,d,e)=>(f._OrtAppendExecutionProvider=O._)(a,b,c,d,e);f._OrtAddFreeDimensionOverride=(a,b,c)=>(f._OrtAddFreeDimensionOverride=O.$)(a,b,c);
f._OrtAddSessionConfigEntry=(a,b,c)=>(f._OrtAddSessionConfigEntry=O.aa)(a,b,c);f._OrtReleaseSessionOptions=a=>(f._OrtReleaseSessionOptions=O.ba)(a);f._OrtCreateSession=(a,b,c)=>(f._OrtCreateSession=O.ca)(a,b,c);f._OrtReleaseSession=a=>(f._OrtReleaseSession=O.da)(a);f._OrtGetInputOutputCount=(a,b,c)=>(f._OrtGetInputOutputCount=O.ea)(a,b,c);f._OrtGetInputOutputMetadata=(a,b,c,d)=>(f._OrtGetInputOutputMetadata=O.fa)(a,b,c,d);f._OrtFree=a=>(f._OrtFree=O.ga)(a);
f._OrtCreateTensor=(a,b,c,d,e,g)=>(f._OrtCreateTensor=O.ha)(a,b,c,d,e,g);f._OrtGetTensorData=(a,b,c,d,e)=>(f._OrtGetTensorData=O.ia)(a,b,c,d,e);f._OrtReleaseTensor=a=>(f._OrtReleaseTensor=O.ja)(a);f._OrtCreateRunOptions=(a,b,c,d)=>(f._OrtCreateRunOptions=O.ka)(a,b,c,d);f._OrtAddRunConfigEntry=(a,b,c)=>(f._OrtAddRunConfigEntry=O.la)(a,b,c);f._OrtReleaseRunOptions=a=>(f._OrtReleaseRunOptions=O.ma)(a);f._OrtCreateBinding=a=>(f._OrtCreateBinding=O.na)(a);
f._OrtBindInput=(a,b,c)=>(f._OrtBindInput=O.oa)(a,b,c);f._OrtBindOutput=(a,b,c,d)=>(f._OrtBindOutput=O.pa)(a,b,c,d);f._OrtClearBoundOutputs=a=>(f._OrtClearBoundOutputs=O.qa)(a);f._OrtReleaseBinding=a=>(f._OrtReleaseBinding=O.ra)(a);f._OrtRunWithBinding=(a,b,c,d,e)=>(f._OrtRunWithBinding=O.sa)(a,b,c,d,e);f._OrtRun=(a,b,c,d,e,g,h,p)=>(f._OrtRun=O.ta)(a,b,c,d,e,g,h,p);f._OrtEndProfiling=a=>(f._OrtEndProfiling=O.ua)(a);var L=()=>(L=O.va)();f._free=a=>(f._free=O.wa)(a);f._malloc=a=>(f._malloc=O.xa)(a);
var ya=(a,b,c,d,e,g)=>(ya=O.Aa)(a,b,c,d,e,g),Ca=()=>(Ca=O.Ba)(),Ob=(a,b,c,d,e)=>(Ob=O.Ca)(a,b,c,d,e),Tb=a=>(Tb=O.Da)(a),Xb=a=>(Xb=O.Ea)(a),hc=(a,b)=>(hc=O.Fa)(a,b),bc=()=>(bc=O.Ga)(),Vb=(a,b)=>(Vb=O.Ha)(a,b),W=a=>(W=O.Ia)(a),Nb=a=>(Nb=O.Ja)(a),Mb=()=>(Mb=O.Ka)();function oc(){var a=O;a=Object.assign({},a);var b=d=>()=>d()>>>0,c=d=>e=>d(e)>>>0;a.va=b(a.va);a.xa=c(a.xa);a.Ja=c(a.Ja);a.Ka=b(a.Ka);return a}f.stackSave=()=>Mb();f.stackRestore=a=>W(a);f.stackAlloc=a=>Nb(a);
f.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":F()[a>>>0]=b;break;case "i8":F()[a>>>0]=b;break;case "i16":sa()[a>>>1>>>0]=b;break;case "i32":I()[a>>>2>>>0]=b;break;case "i64":E[a>>>3]=BigInt(b);break;case "float":ta()[a>>>2>>>0]=b;break;case "double":K()[a>>>3>>>0]=b;break;case "*":J()[a>>>2>>>0]=b;break;default:R(`invalid type for setValue: ${c}`)}};
f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return F()[a>>>0];case "i8":return F()[a>>>0];case "i16":return sa()[a>>>1>>>0];case "i32":return I()[a>>>2>>>0];case "i64":return E[a>>>3];case "float":return ta()[a>>>2>>>0];case "double":return K()[a>>>3>>>0];case "*":return J()[a>>>2>>>0];default:R(`invalid type for getValue: ${b}`)}};f.UTF8ToString=Eb;f.stringToUTF8=Y;
f.lengthBytesUTF8=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function pc(){if(0<P)Q=pc;else if(q)k(f),Da();else{for(;0<Ib.length;)Ib.shift()(f);0<P?Q=pc:(f.calledRun=!0,B||(Da(),k(f)))}}pc();f.PTR_SIZE=4;moduleRtn=aa;


  return moduleRtn;
}
);
})();
export default ortWasmThreaded;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = (await import('worker_threads')).workerData === 'em-pthread';

// When running as a pthread, construct a new instance on startup
isPthread && ortWasmThreaded();
